version: '3'
services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - my_network
  redis:
    image: redis
    container_name: db
    ports:
      - "4000:4000"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
